### ISSUE TITLE
Crash if onError property is not defined

### ISSUE THREAD

**Issue by aabherve** [q-rapids/qrapids-eval#1]
If the parameter property "onError" property is not define in {metrcname}.property file, qr-eval crash.

```
java.lang.NullPointerException
	at eval2.QueryDef.getProperty(QueryDef.java:83)
	at eval2.EvalProject.executeMetricQueries(EvalProject.java:437)
	at eval2.EvalProject.run(EvalProject.java:95)
	at eval2.Eval.main(Eval.java:86)
juin 03, 2019 4:52:07 PM eval2.Eval main
```

The possibility of a null value in adressed on EvalProject class but not on  **getProperty()** methode of the **QueryDef** class.

EvalProject : 

```
String onError = metricQueryDef.getProperty("onError");
if ( onError == null ) {
	onError = projectErrorStrategy;
}
```

QueryDef

```
	public String getProperty( String key ) {	
		String propValue = props.getProperty(key);
		if ( propValue.startsWith("$$") ) {
			return projectProperties.getProperty( propValue.substring(2) );
		} else {
			return propValue;
		}
	}
```

should be

	public String getProperty( String key ) {	
		String propValue = props.getProperty(key);
                if ( propValue == null ){
                       return null;
                }
		if ( propValue.startsWith("$$") ) 
			return projectProperties.getProperty( propValue.substring(2) );
		} else {
			return propValue;
		}
	}

**Comment by wickenkamp** [comment]
Thanks!
